
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcshydrusnuxsxwctnod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjc2h5ZHJ1c251eHN4d2N0bm9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMTEzNzIsImV4cCI6MjA1NzU4NzM3Mn0.eLmaLDHcy1yAu_eRpPsds6sab8MiU1wBopO20NJAzF4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Function to fetch drugs from the database based on search criteria
export interface FetchDrugsParams {
  searchTerm?: string;
  category?: string;
  limit?: number;
  userSubscriptionLimit?: number; // Add subscription-based limit
}

export const fetchDrugs = async ({ 
  searchTerm, 
  category,
  limit = 100, // Default limit
  userSubscriptionLimit // Subscription-based limit override
}: FetchDrugsParams) => {
  console.log("Fetching drugs from Supabase with params:", { searchTerm, category, limit, userSubscriptionLimit });
  
  // Use subscription limit if provided and it's lower than the default limit
  const effectiveLimit = userSubscriptionLimit && userSubscriptionLimit < limit ? userSubscriptionLimit : limit;
  
  try {
    let query = supabase
      .from('drugs')
      .select('*')
      .limit(effectiveLimit);
    
    if (searchTerm) {
      // Search in name, generic_name, drug_class, manufacturer, and description
      query = query.or(
        `name.ilike.%${searchTerm}%,generic_name.ilike.%${searchTerm}%,drug_class.ilike.%${searchTerm}%,manufacturer.ilike.%${searchTerm}%,description.ilike.%${searchTerm}%`
      );
    }
    
    if (category) {
      query = query.eq('category', category);
    }
    
    const { data, error } = await query;
    
    if (error) {
      console.error('Error fetching drugs:', error);
      return [];
    }
    
    console.log(`Retrieved ${data?.length || 0} drugs from Supabase (limit: ${effectiveLimit})`);
    return data;
  } catch (e) {
    console.error("Exception fetching from Supabase:", e);
    return [];
  }
};
