
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcshydrusnuxsxwctnod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjc2h5ZHJ1c251eHN4d2N0bm9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMTEzNzIsImV4cCI6MjA1NzU4NzM3Mn0.eLmaLDHcy1yAu_eRpPsds6sab8MiU1wBopO20NJAzF4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Drug data helper functions
export interface DrugDataParams {
  searchTerm?: string;
  category?: string; 
  limit?: number;
}

export async function fetchDrugs(params: DrugDataParams = {}) {
  const { searchTerm, category, limit = 50 } = params;
  
  let query = supabase.from('drugs').select('*');
  
  if (searchTerm) {
    query = query.or(`name.ilike.%${searchTerm}%,generic_name.ilike.%${searchTerm}%`);
  }
  
  if (category) {
    query = query.eq('category', category);
  }
  
  const { data, error } = await query.limit(limit);
  
  if (error) {
    console.error('Error fetching drugs:', error);
    return null;
  }
  
  return data;
}

export async function fetchDrugById(id: string) {
  const { data, error } = await supabase
    .from('drugs')
    .select('*')
    .eq('id', id)
    .single();
  
  if (error) {
    console.error('Error fetching drug by ID:', error);
    return null;
  }
  
  return data;
}

export async function saveDrugIdentification(identificationData: any) {
  const { data, error } = await supabase
    .from('drug_identifications')
    .insert([identificationData])
    .select();
  
  if (error) {
    console.error('Error saving drug identification:', error);
    return null;
  }
  
  return data;
}

// Enhanced drug search with fuzzy matching support
export async function searchDrugsByFeatures(params: {
  name?: string;
  imprint?: string;
  color?: string;
  shape?: string;
  markings?: string;
  limit?: number;
}) {
  const { name, imprint, color, shape, markings, limit = 10 } = params;
  
  let query = supabase.from('drugs').select('*');
  
  // Build query based on available parameters
  if (name) {
    query = query.or(`name.ilike.%${name}%,generic_name.ilike.%${name}%,brand_names.cs.{${name}}`);
  }
  
  // Add other search criteria if provided
  if (color) {
    query = query.ilike('description', `%${color}%`);
  }
  
  if (shape) {
    query = query.ilike('description', `%${shape}%`);
  }
  
  if (imprint || markings) {
    const searchTerm = imprint || markings;
    query = query.or(`description.ilike.%${searchTerm}%,name.ilike.%${searchTerm}%`);
  }
  
  const { data, error } = await query.limit(limit);
  
  if (error) {
    console.error('Error searching drugs by features:', error);
    return null;
  }
  
  return data;
}

// Function to fetch possible drug matches by description
export async function findSimilarDrugs(description: string, limit = 5) {
  if (!description || description.length < 3) {
    return null;
  }
  
  // Extract key terms from the description
  const keyTerms = description
    .toLowerCase()
    .replace(/[^\w\s]/g, '')
    .split(/\s+/)
    .filter(term => term.length > 3 && !['drug', 'tablet', 'capsule', 'pill', 'medication', 'medicine', 'the', 'and', 'with'].includes(term));
  
  if (keyTerms.length === 0) {
    return null;
  }
  
  // Build a query with the key terms
  let query = supabase.from('drugs').select('*');
  
  // Add each key term to search in the name, generic name, or description
  const searchConditions = keyTerms.map(term => `name.ilike.%${term}%,generic_name.ilike.%${term}%,description.ilike.%${term}%`);
  query = query.or(searchConditions.join(','));
  
  const { data, error } = await query.limit(limit);
  
  if (error) {
    console.error('Error finding similar drugs:', error);
    return null;
  }
  
  return data;
}
