// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcshydrusnuxsxwctnod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjc2h5ZHJ1c251eHN4d2N0bm9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMTEzNzIsImV4cCI6MjA1NzU4NzM3Mn0.eLmaLDHcy1yAu_eRpPsds6sab8MiU1wBopO20NJAzF4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);